### PR TITLE
added support for CSV streaming renderer

### PR DESCRIPTION
**Pull request by ivancrneto**
Hi,

I just created a class CSVStreamingRenderer that renders the CSV data by returning a generator, which is required for using in Django StreamingHttpResponse.

I put some docs explaining how to use it.

### CODE REVIEW

**Comment by int-ua** [comment]
What about CSVStreamingRendererWithUnderscores?

**Comment by alessio** [comment]
@ivancrneto could you please provide some docs?

**Comment by ivancrneto** [comment]
@alessio looks like it doesn't work because of the `tablize` function. We need to rework it so it don't access all data

**Comment by alessio** [comment]
Alright, I see, thanks!

**Comment by aidanlister** [comment]
Our data sets are so big that without streaming the browser / server times out, so we did this hacky approach:

```
class JSONApiCSVRenderer(csv_renderers.CSVStreamingRenderer):
    def flatten_list(self, l):
        return {'items': ','.join(str(pk) for pk in l)}

    def render(self, data, media_type=None, renderer_context={}):
        if 'queryset' not in data:
            return data

        csv_buffer = Echo()
        csv_writer = csv.writer(csv_buffer)
        if data['queryset'].count() > 0:
            yield csv_writer.writerow([
                elem[0]
                for elem
                in self.flatten_data([data['serializer'](data['queryset'].first()).data])[0].items()
            ])

        generator = (
            self.flatten_data([data['serializer'](item).data])[0] for item in data['queryset']
        )
        for row in generator:
            yield csv_writer.writerow([
                elem.encode('utf-8') if isinstance(elem, text_type) and PY2 else elem
                for _, elem in row.items()
            ])


class V2Mixin(object):
    pagination_class = V2Pagination
    parser_classes = (
        rest_framework_json_api.parsers.JSONParser,
        rest_framework.parsers.FormParser,
        rest_framework.parsers.MultiPartParser,
    )
    renderer_classes = (
        rest_framework_json_api.renderers.JSONRenderer,
        rest_framework.renderers.BrowsableAPIRenderer,
        JSONApiCSVRenderer,
    )
    metadata_class = rest_framework_json_api.metadata.JSONAPIMetadata

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        if isinstance(request.accepted_renderer, JSONApiCSVRenderer):
            return StreamingHttpResponse(request.accepted_renderer.render({
                'queryset': queryset,
                'serializer': self.get_serializer_class(),
            }))
        else:
            page = self.paginate_queryset(queryset)
            if page is not None:
                serializer = self.get_serializer(page, many=True)
                data = serializer.data
                return self.get_paginated_response(data)
            else:
                serializer = self.get_serializer(queryset, many=True)
                return Response(serializer.data)
```

**Pull request merged**
