### PR TITLE
feat: add test for django32

### PR DESCRIPTION
**Pull request by MaferMazu**
I would like to add support to django 3.2 ( #90 )

I just added django 3.2 in the tests and created a file in requirements following what you already had.

I hope you can approve the PR or improve it and then make a release with django 3.2 support.

I will be attentive.
Greetings.

### CODE REVIEW

**Comment by UsamaSadiq** [comment]
@mjumbewu could we have a review on this PR? Thanks.

**Comment by Aiky30** [comment]
https://github.com/mjumbewu/django-rest-framework-csv/issues/97

**Comment by Mte90** [comment]
ping @mjumbewu

**Comment by mjumbewu** [comment]
Thank you for this! As you can see there were many people awaiting an update on this package, and the latest versions of Django are now supported as of [release 3.0.0](https://github.com/mjumbewu/django-rest-framework-csv/releases/tag/3.0.0).

**Pull request closed without merging**
