### PR TITLE
Writer opts

### PR DESCRIPTION
**Pull request by moumoutte**
Same as this closed pull request , but the branch is different from my repository. Sorry for the double PR.

Refere to : https://github.com/mjumbewu/django-rest-framework-csv/pull/26

### CODE REVIEW

**Comment by moumoutte** [comment]
https://github.com/mjumbewu/django-rest-framework-csv/pull/26

**Comment by moumoutte** [comment]
@mjumbewu The build fails because of six was not found.. Do you know how can I fix this ?

**Comment by mjumbewu** [comment]
Sorry I'm just getting around to this. @moumoutte The build was failing because the latest DRF doesn't support Django 1.3 (which didn't have `six` included). I've dropped support for Django 1.3, so all should be well. If you can, would you add a simple test or two to the `tests.TestCSVRenderer` test case?

**Comment by moumoutte** [comment]
Just one test has been added, but it covered the common case as delimiter, quotingchar, quoting strategy. @mjumbewu  Is it enough ?

**Comment by moumoutte** [comment]
@mjumbewu , can I have an update on this PR ? Thank you :)

**Comment by mjumbewu** [comment]
Sure, looks good to me. Merging in. I'll make a new release some time this week.

I was thinking that it would be good, as part of this, to have a `writer_opts` attribute on the actual class. Or maybe (better yet?) an overridable `get_writer` method. I'll think about that.

**Comment by moumoutte** [comment]
get_writer could be great, with a get_writer_kwargs argument may be ?

 like

   def get_writer(self):
        return self.writer_class(**self.get_writer_kwargs())

Something like that ?

**Comment by moumoutte** [comment]
Anyway, thank you for the merge.

**Pull request merged**
