### PR TITLE
add file bom.

### PR DESCRIPTION
**Pull request by Yaoxin**

### CODE REVIEW

**Comment by fabienheureux** [comment]
What is the status on this PR ? Would love to see it merged

**Comment by alevine** [comment]
If the build passes could this potentially get merged? It would be super helpful!

**Comment by mjumbewu** [comment]
@alevine Hey, yes, but it looks like there are some updates to the tests that need to happen (just seems like [bit rot](https://en.wikipedia.org/wiki/Software_rot)). I'll be able to put some time into it in the next couple weeks, but I'm happy to accept a PR to update the tox file if you can get to it first.

**Comment by mjumbewu** [comment]
This was merged as part of #86

**Comment by alevine** [comment]
@mjumbewu Thank you for such a quick fix! I'll be looking forward to the release

**Pull request closed without merging**
